rng(0)
data(:,1) = 0.5 : 0.1 : 3;
data(:,1) = data(:,1) + 0.2*randn(size(data(:,1)));
data(:,2) = 3 + 0.2 * exp(data(:,1));
data(:,2) = data(:,2) + 0.5*randn(size(data(:,2)));
data = sortrows(data,1);
data(:,3) = abs(randn(size(data(:,1))));
data(:,4) = sum(data(:,3))./data(:,3);
model = @(phi,t)(phi(1)*exp(t) + phi(2));
p0 = [0 0];
p = nlinfit(data(:,1),data(:,2),model,p0);
fittedcurve_1 = p(1)*exp(data(:,1)) + p(2);
model = @(phi,t)(phi(1)*exp(t) + phi(2));
p0 = [0 0];
p = nlinfit(data(:,1),data(:,2),...
   model,p0,'Weights',data(:,4))
fittedcurve_2 = p(1)*exp(data(:,1)) + p(2);
figure1 = figure(...
    'Position',[200 200 800 600],...
    'Color',[1 1 1]);
axes1 = axes(...
    'Box','on',...
    'XLim',[0 3.5],...
    'YLim',[0 10],...
    'Units','Centimeters',...
    'Position',[2 2 10 6],...
    'LineWidth',0.6,...
    'FontName','Helvetica',...
    'FontSize',8);
hold on
errorbar1 = errorbar(...
    data(:,1),data(:,2),data(:,3),...
    'Marker','o',...
    'MarkerEdgeColor',[0 0 0],...
    'MarkerFaceColor',[0 0.4453 0.7383],...
    'Color',[0 0 0],...
    'LineStyle','none');
line1 = line(data(:,1),fittedcurve_1,...
    'LineWidth',0.75,...
    'Color',[0.8477 0.3242 0.0977]);
line2 = line(data(:,1),fittedcurve_2,...
    'LineWidth',0.75,...
    'Color',[0.9258 0.6914 0.1250]);
xlabel1 = xlabel(...
    'Depth in Sediment (meters)',...
    'FontName','Helvetica',...
    'FontSize',8);
ylabel1 = ylabel(...
    'Age of Sediment (kyrs)',...
    'FontName','Helvetica',...
    'FontSize',8);
title1 = title(...
    'Comparison of Unweighted and Weighted Fit',...
    'FontName','Helvetica',...
    'FontSize',9);
legend1 = legend('Nonlinear Regression',...
    'Weighted Nonlinear Regression',...
    'Data with Errors',...
    'Location','Northwest');
legend1.Box = 'off';
print -depsc2 -cmyk afig_4_9.eps
print -dpng -r300 afig_4_9.png